export default function randomCatText() {
  let text = [
    "The frequency of a domestic cat's purr is the same at which muscles and bones repair themselves.",
    "By the time a cat is 9 years old, it will only have been awake for three years of its life.",
    "Cat owners are 17% more likely to have a graduate degree than non cat owners.",
    "The Egyptian Mau’s name is derived from the Middle Egyptian word mjw, which means cat. But contrary to its name, it’s unclear whether the modern Egyptian Mau actually originated in Egypt.",
    "Cats aren’t the only animals that purr — squirrels, lemurs, elephants, and even gorillas purr too.",
    "Cats can distinguish different flavors in water.",
    "Every year, nearly four million cats are eaten in China as a delicacy.",
    "Here is a video of some cats in zero gravity. youtu.be/O9XtK6R1QAk",
    "America’s cats, including housecats that adventure outdoors and feral cats, kill between 1.3 billion and 4.0 billion birds in a year.",
    "The special sensory organ called the Jacobson's organ allows a cat to have 14 times the sense of smell of a human. It consists of two fluid-filled sacs that connect to the cat's nasal cavity.",
    "Wikipedia has a recording of a cat meowing, because why not?",
    "Scottish sailer Alexander Selkirk once survived for 4 years on a deserted island thanks to feral cats that protected him from large rats during the night.",
    "There are cats who have survived falls from over 32 stories (320 meters) onto concrete.",
    "Most cats don't like water because their coats do not insulate them well enough.",
    "A cat’s nose pad is ridged with a unique pattern, just like the fingerprint of a human.",
    "The technical term for 'hairball' is 'bezoar.'",
    "Cats make more than 100 different sounds whereas dogs make around 10.",
    "A cat's brain is 90% similar to a human's — more similar than to a dog's.",
    "Cats can survive falls from up to 65 feet or more.",
    "In 1879, Belgium unsuccessfully tried to use cats to deliver mail.",
    "The myth that a cat has nine lives comes from their ability to jump and land from high places. The number 9 is believed by some to originate from William Shakespeare's Romeo and Juliet.",
    "From Romeo & Juliet: 'A cat has nine lives. For three he plays, for three he strays, and for the last three he stays.'",
    "Exposure to UV light with hairless or partially-hairless cats can result in sunburn, even during cloudy or shady conditions. If your cat risks overexposure, consider applying sunscreen daily.",
    "Evidence suggests domesticated cats have been around since 3600 B.C., 2,000 years before Egypt's pharaohs.",
    "Since cats treat us like cats and depend on us for things like food, water, and opening the door to let them out, they do recognize that we are in some way in charge — the “big cat” in the shared territory.",
    "Cats have fur",
    "Cats are the most popular pet in the United States: There are 88 million pet cats and 74 million dogs.",
    "In tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.",
    "The world's richest cat is worth $13 million after his human passed away and left her fortune to him.",
    "When cats grimace, they are usually 'taste-scenting.' They have an extra organ that, with some breathing control, allows the cats to taste-sense the air.",
    "A cat's purr may be a form of self-healing, as it can be a sign of nervousness as well as contentment.",
    "Your cat recognizes your voice but just acts too cool to care (probably because they are).",
    "Cats have a longer-term memory than dogs, especially when they learn by actually doing rather than simply seeing.",
    "Polydactyl cats are also referred to as 'Hemingway cats' because the author was so fond of them.",
    "When asked if her husband had any hobbies, Mary Todd Lincoln is said to have replied 'cats.'",
    "Cats can change their meow to manipulate a human. They often imitate a human baby when they need food, for example.",
    "One legend claims that cats were created when a lion on Noah's Ark sneezed and two kittens came out.",
    "In Korea and Japan, there is a Cat Cafe where you can go to drink coffee and hang out with cats for hours.",
    "When cats leave their poop uncovered, it is a sign of aggression to let you know they don't fear you.",
    "Owning a cat can reduce the risk of heart attacks and strokes by more than a third, researchers found.",
    "Cucumbers look enough like a snake to cause a cat's instinctive fear of snakes to kick in, causing it to panic and flee.",
    "Lil' Bunny Sue Roux is a cat who was born with no front legs, and walks upright like a kangaroo. https://www.instagram.com/lilbunnysueroux",
    "Some Siamese cats appear cross-eyed because the nerves from the left side of the brain go to mostly the right eye and the nerves from the right side of the brain go mostly to the left eye.",
    "Owning a cat can reduce the risk of stroke and heart attack by a third.",
    "In Islam, cats are revered for their cleanliness. Muhammad is reported to have said that 'a love of cats is an aspect of faith'.",
    "A cat named Emmy lived aboard the RMS Empress of Ireland and she never missed a voyage. On May 28,1914, however, she refused to board. The ship left without her and then sank the following day.",
    "Domestic cats will try not to drink from a water bowl that is next to their food. This is because in the wild, water next to their kill could be contaminated.",
    "A Chinese cat named Baidianr (meaning 'white spot') had a unique ability to choose World Cup winners. He predicted the winner of the soccer competition 6 years in a row.",
    "Cats have a layer called the tapetum lucidum just behind their retina which reflects light inside the eye, helping it capture more light. This reflected light is the glow you see when taking a photo of a cat with the flash on.",
    "Most cats are lactose intolerant, and milk can cause painful stomach cramps and diarrhea. It's best to forego the milk and just give your cat the standard: clean, cool drinking water.",
    "When cats run, their backs contract and extend to give them maximum stride. Their shoulder blades are not attached with bone, but with muscle, and this gives a cat even greater extension and speed.",
    "In most US states, declawing cats is legal but in the European Union it is not.",
    "Kittens sleep so much because the growth hormone is only released when they sleep.",
    "It has been estimated that a cat yawns on the average of 109,500 times in his life.",
    "A cat can jump up to six times its length.",
    "Cats only sweat through their foot pads.",
    "A female cat is called a “molly” or a “queen”.",
    "Black cats are less likely to be adopted because of their 'appearance'.",
    "Cats were mythic symbols of divinity in ancient Egypt.",
    "Cats have 38 chromosomes in each zygote cell.",
    "If they have ample water, cats can tolerate temperatures up to 133 °F.",
    "Your cat's instincts tell her that a paperweight or knickknack could turn out to be a mouse. Her poking paw would send it scurrying, giving her a good game.",
    "For a cat at rest, the average heart rate usually is between 150 and 180 bpm, more than twice that of a human, which averages 70 bpm.",
    "Compared to other felines, domestic cats have narrowly spaced canine teeth, adapted to their preferred prey of small rodents.",
    "Cats, like dogs, are digitigrades. They walk directly on their toes, with the bones of their feet making up the lower part of the visible leg.",
    "A cat's kidneys are so efficient, it can survive on a diet consisting only of meat, with no additional water, and can even rehydrate by drinking seawater.",
    "Most breeds of cat have a noted fondness for settling in high places, or perching. In the wild, a higher place may serve as a concealed site from which to hunt.",
    "The ability of a cat to reflexively twist its body and balance itself during a fall is known as the 'cat righting reflex'.",
    "The cat's tongue has backwards-facing spines about 500 µm long, which are called papillae. These contain keratin which makes them rigid so the papillae act like a hairbrush.",
    "A cat can die from essential oils",
    "Hearing is the strongest of cat's senses: They can hear sounds as high as 64 kHz — compared with humans, who can hear only as high as 20 kHz.",
    "Cats have free-floating clavicle bones that attach their shoulders to their forelimbs, which allows them to squeeze through very small spaces.",
    "Colonel Meow, a Himalayan-Persian mix who became famous on social media websites for his extremely long fur and scowling face, holds the Guinness world record for longest hair on a cat (nine inches).",
    "Towser 'The Mouser' of Glenturret Distillery in Crieff, Scotland, holds the Guinness World Record for the most mice caught (28,899).",
    "A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.",
    "The cat who holds the record for the longest non-fatal fall is Andy. He fell from the 16th floor of an apartment building (about 200 ft/.06 km) and survived.",
    "A cat’s eyesight is both better and worse than humans. It is better because cats can see in much dimmer light and they have a wider peripheral view. It’s worse because they don’t see color as well as humans do.",
    "The lightest cat on record is a blue point Himalayan called Tinker Toy, who weighed 1 pound, 6 ounces (616 g). Tinker Toy was 2.75 inches (7 cm) tall and 7.5 inches (19 cm) long.",
    "The first cartoon cat was Felix the Cat in 1919. In 1940, Tom and Jerry starred in the first theatrical cartoon “Puss Gets the Boot.”",
    "In 1981 Andrew Lloyd Weber created the musical Cats, based on T.S. Eliot’s Old Possum’s Book of Practical Cats.",
    "The claws on the cat’s back paws aren’t as sharp as the claws on the front paws because the claws in the back don’t retract and, consequently, become worn.",
    "The most traveled cat is Hamlet, who escaped from his carrier while on a flight. He hid for seven weeks behind a panel on the airplane. By the time he was discovered, he had traveled nearly 373,000 miles (600,000 km).",
    "The little tufts of hair in a cat’s ear that help keep out dirt direct sounds into the ear, and insulate the ears are called 'ear furnishings.'",
    "The Australian Wildlife Conservancy completed a 44km cat-proof fence in 2018 to prevent feral cats from entering the Newhaven wildlife sanctuary, who kill about a million native birds every night across Australia.",
    "Black cats are bad luck in the United States, but they are good luck in the United Kingdom and Australia.",
    "The cat skull is unusual among mammals in having very large eye sockets and a powerful and specialized jaw.",
    "Cats have scent glands along their tail, their forehead, lips, chin, and the underside of their front paws.",
    "The french tuxedo kitty, Félix, aka 'Astrocat', was the first cat to go to space. She survived the trip.",
    "A male cat is called a tom.",
    "Issac Newton decided to invent the cat flap because his own cat, Spithead, kept opening the door and spoiling his light experiments.",
    "Thank to an extremely efficient pair of kidneys, cats can hydrate themselves by drinking salt water.",
    "A cats whiskers are the exact width of their body.",
    "At night, Disneyland is overrun by cats. The theme park feeds them and takes care of them though, because they keep the rodent population in check.",
    "Cats lack antibodies against dog blood so they can only receive it via a transfusion once. The second time would kill them.",
    "The Indiana State Prison allows prisoners to adopt a cat and keep it in their cell. They are meant to improve the mood of the prisoners.",
    "Oftentimes shelters won't let black cats be adopted around Halloween out of a fear that they may be sacrificed.",
    "When cats bring dead animals back to their humans, they are 'teaching them to hunt' as they would with a younger cat.",
    "Cat fanciers bred and exhibited Maus in Europe until World War II, when attention toward the cat waned and it nearly went extinct.",
    "The Egyptian Mau breed was saved from extinciton when Russian princess Natalie Trubetskaya was given a Mau that was imported from the Middle East. When she emigrated to New York City in 1956, she brought along three Mau cats.",
    "Unlike kittens, adult cats don’t release any particular key hormones during sleep. They snooze all day just because they can. :)",
    "Russian scientists discovered in the 1930s that Siamese kittens kept in very warm rooms didn't develop the breed's signature dark patches.",
    "Cats have a third eyelid called a “haw”. It’s generally only visible when they’re unwell.",
    "In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat.",
    "A cat was mayor of Talkeetna, Alaska, for 20 years. His name is Stubbs, and he died on July 23, 2017.",
    "Many people think that the Turkish Van is simply a color variation of the Turkish Angora, but in fact, they are distinct breeds that developed in different parts of Turkey.",
    "The Bengal is the result of crossbreeding between domestic cats and Asian leopard cats, and its name is derived from the scientific name for the Asian leopard cat (Felis bengalensis).",
    "Despite its traditionally wild roots, the Bengal is domestic and will gladly make itself in the indoor 'jungle' of your home.",
    "Cats cannot see in total darkness, however their vision is much better than a human's in semidarkness because their retinas are much more sensitive to light.",
    "The gene that codes orange fur is on the X chromosome, so female cats must inherit two orange genes to end up with orange fur, while male cats only need one.",
    "The Manx hails from the Isle of Man in the Irish Sea, and many Manx are tailless, a condition believed to have been caused by a dominant genetic mutation that spread among the island's cat population.",
    "Leonardo da Vinci created a series of drawings titled 'Study of Cat Movements and Positions', which consists of more than twenty drawings of cats and lions lying asleep, sitting, playing, and fighting.",
    "The Chartreux is distinguished by a woolly blue-grey coat, a robust body poised over small paws, and full cheeks with a mouth that always appear to be smiling.",
    "While Chartreux cats aren't very vocal, they are sociable and communicate through eye contact and body language.",
    "Cats love playing with yarn, ribbons, and fishing-rode style toys. However, cats should not be left alone with anything that they could get tangled in.",
    "All Scottish Folds descended from Susie, a white barn cat discovered in Scotland in the early 1960s. Susie sported the breed's folded ears – the result of a genetic mutation – and passed on the trait through breeding.",
    "Mark Twain was undeniably an ailurophile. He had up to 19 cats at one time and gave them such memorable names as Beelzebub, Buffalo Bill, and Soapy Sal.",
    "Abraham Lincoln, being the ailurophile that he was, once rescued three stray kittens and ensured that they were fed and found homes.",
    "The Sphynx was originally known as the Canadian Hairless Cat. The breed originated in Toronto, and was renamed to Sphynx, a nod to the famous limestone sculpture in the Egyptian Desert.",
    "A cat’s spine can rotate more than the spines of most other animals, and their vertebrae have a special, flexible, elastic cushioning on the disks, which gives it even more flexibility.",
    "Cats have been domesticated for around 4,000 years. While they were once valued for their hunting abilities, they are now valued for their companionship and loving behavior.",
    "The most popular pedigreed cat in North America is the Persian cat, followed by the Main Coon and the Siamese cat.",
    "In the early 1980s, a Chinchilla Persian cat named Jemari Sanquist mated with a Lilac Burmese named Bambino Lilac Fabergé, producing the Burmilla breed.",
    "A large number of cats inhabit the Largo di Torre Argentina, an ancient Roman temple site near where Caesar was killed. Local volunteers care for the cats.",
    "The Norwegian Forest Cat is called 'skogcatt' in its homeland of Norway and plays a role in the Norwegian fairy tales and legends.",
    "The Abyssinian, the Siamese, and the American Shorthair were crossbred to produce the Ocicat breed.",
    "Some animal shelters require kittens be adopted in pairs to ensure they came from the same litter.",
    "The Havana Brown breed hails from England, where it was created by crossbreeding Siamese cats with domestic black cats.",
    "The wild-looking but domestic Ocicat is named for its resemblance to the ocelot, a small South American wild cat.",
    "Cats are among only a few animals that walk by moving their two right legs one after another and then their two left legs, rather than moving diagonal limbs simultaneously.",
    "The Turkish Van is often called the 'swimming cat' because they are naturals in the water, thanks in part to their uniquely textured, water-resistant coat.",
    "GitHub is a cloud source version control system where its mascot is an octocat, an anthropomorphized cat with five tentacles.",
    "About one in two cats respond to catnip, and only develop a sensitivity to it at around 3 to 6 months of age.",
    "Due to the controversy, though loved by most, the Kashmir is overlooked by many cat fanciers.",
    "The domestic cat (Felis catus) is a small, typically furry, carnivorous mammal.",
    "Blackie became the richest cat in history when he inherited 15 million British Pounds.",
    "Cats have about 130,000 hairs per square inch (20,155 hairs per square centimeter).",
    "Many Egyptians worshipped the goddess Bast, who had a woman’s body and a cat’s head.",
    "The average female housecat could give birth to ove 100 kittens in her lifetime.",
    "Cats don't go through menopause, so they can continue to breed into their senior years.",
    "Cats like being brushed by their owners, because it reminds them of their mother.",
    "Loyal, playful, and alert, Manx are considered to be more 'doglike' than other cats.",
    "When kittens ages to weeks five and six, they should start making the transition to dry food.",
    "Legend holds that the Chartreux once lived alongside the Carthusian monks of France.",
    "A cat has 244 bones in its entire body—even more than a human, who only has 206 bones.",
    "The fear of cats is called 'Ailurophobia.'",
    "Cat owners are 25% likely to pick George Harrison as their favorite Beatle.",
    "Only 11.5% of people consider themselves 'cat people.'",
    "'Cat people' are 11% more likely to be introverted than others.",
    "The Bombay cat breed was developed to resemble a miniature panther.",
    "Cats use their whiskers to judge whether they’ll fit through a space.",
    "The softest part of a cat is most definitely its cheek area.",
    "When a cat yawns, it's mouth opens so wide that you can count every tooth.",
    "Cats can have three litters a year, or approximately 12 kittens.",
    "The collective noun for kittens is a 'kindle'.",
    "The cheetah is the only cat that doesn't have retractable claws.",
    "Norwegian Forest Cats are usually very people friendly.",
    "Courgars are the largest wild cats that can purr.",
    "Dr. Seuss wrote The Cat in the Hat using only 236 words.",
    "Cats conserve energy by sleeping for an average of 13 to 14 hours a day.",
    "Some cats do not eat fish.",
    "Cats can climb on trees faster than squirels.",
    "A house cat is faster than Usain Bolt.",
    "In Norse mythology, the goddess Freya travels in a chariot pulled by two cats—specifically Norwegian Forest Cats.",
    "American Curl kittens are born with straight ears, but the ears begin to curl back after just a few days.",
    "The pink substance inside a cat's nail is called the 'quick' or the 'dermis'. When trimming your cat's nails, be sure to only cut the upper white part of the nail, not the quick.",
    "The irresistable and cuddly Ragamuffin is the result of crossbreeding Ragdoll cats with Persians, Himalayans, and other larger longhaired breeds.",
    "Legend holds that a goddess rewarded a temple cat's piety by turning the cat's eyes blue and his coat golden, thus creating the first Birman cat.",
    "While some cats love being brushed, others don't take to it naturally. Try to groom your cat in the same spot at the same time of day to create a sense of routine.",
    "Kittens typically begin to engage in playful behavior at around four weeks of age."
  ];

  let randomTextPick = Math.round( Math.random() * text.length );
  return text[randomTextPick];
}